config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  resources :users, only: %i[new create]
  resources :boards, only: %i[index new show create edit update destroy]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  mount_uploader :board_image, BoardImageUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :boards, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  def own?(object)
    object.user_id == id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :danger

  private

  # ログインしていない場合に指定されたパスにリダイレクト
  def not_authenticated
    redirect_to root_path, danger: t('defaults.flash_message.require_login')
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.includes(:user)
  end

  def new
    @board = Board.new
  end

  def show
    @board = Board.find(params[:id])
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to boards_path, success: t('defaults.flash_message.created', item: Board.model_name.human)
    else
      flash.now[:danger] = t('defaults.flash_message.not_created', item: Board.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to board_path(@board), success: t('defaults.flash_message.updated', item: Board.model_name.human)
    else
      flash.now[:danger] = t('defaults.flash_message.not_updated', item: Board.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy
    redirect_to boards_path, success: t('defaults.flash_message.deleted', item: Board.model_name.human), status: :see_other
  end

  private

  def board_params
    params.require(:board).permit(:title, :body, :board_image, :board_image_cache)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top]

  def top; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_path, success: t('user_sessions.create.success')
    else
      flash.now[:danger] = t('user_sessions.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, success: t('user_sessions.destroy.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('users.create.success')
    else
      flash.now[:danger] = t('users.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.erb
<article class="border">
  <%= link_to board_path(board), class: 'card' do %>
    <div class="aspect-video overflow-hidden">
      <%= image_tag board.board_image_url, class: 'w-full h-full duration-300 object-cover' %>
    </div>
    <div class="p-5">
      <h2 class="text-xl font-bold"><%= board.title %></h2>
      <p class="mt-2 text-base font-medium"><%= board.body %></p>
    </div>
  <% end %>
</article>

app/views/boards/_form.html.erb
<%= form_with model: board, class: 'grid grid-cols-1 gap-5 mt-10' do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="grid grid-cols-1 gap-3">
    <%= f.label :title, class: 'font-medium' %>
    <%= f.text_field :title, class: 'border border-sub-color rounded w-full text-base p-2' %>
  </div>
  <div class="grid grid-cols-1 gap-3">
    <%= f.label :body, class: 'font-medium' %>
    <%= f.text_area :body, class: 'border border-sub-color rounded w-full text-base p-2' %>
  </div>
  <div class="grid grid-cols-1 gap-3">
    <%= f.label :board_image, class: 'font-medium' %>
    <%= f.file_field :board_image, class: '', accept: 'image/*' %>
    <%= f.hidden_field :board_image_cache %>
  </div>
  <div class="my-10 text-center">
    <%= f.submit nil, class: 'inline-block border border-sub-color max-w-[160px] w-full rounded px-4 py-2 bg-white cursor-pointer hover:bg-sub-color hover:text-white duration-300' %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<div class="mx-auto my-10 max-w-3xl w-full px-5 md:my-20">
  <h1 class="text-3xl text-center "><%= t('.title') %></h1>
  <%= render 'form', board: @board %>
</div>

app/views/boards/index.html.erb
<div class="mx-auto my-10 max-w-7xl px-5 md:my-20">
  <% if @boards.present? %>
    <div class="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">
      <%= render @boards %>
    </div>
  <% else %>
    <p class="text-center">掲示板がありません</p>
  <% end %>
</div>

app/views/boards/new.html.erb
<div class="mx-auto my-10 max-w-3xl w-full px-5 md:my-20">
  <h1 class="text-3xl text-center "><%= t('.title') %></h1>
  <%= render 'form', board: @board %>
</div>

app/views/boards/show.html.erb
<div class="mx-auto my-10 max-w-7xl px-5 md:my-20">
  <article class="mx-auto max-w-3xl">
    <div class="max-w-lg mx-auto">
      <%= image_tag @board.board_image_url, class: 'object-contain w-full' %>
    </div>
    <div class="mt-5 md:mt-10">
      <h1 class="text-xl font-bold md:text-2xl"><%= @board.title %></h1>
      <p class="mt-3 md:text-lg"><%= @board.body %></p>
    </div>
  </article>
  <% if current_user.own?(@board) %>
    <div class="flex gap-5 justify-center mt-10 text-center">
      <%= link_to '編集する', edit_board_path, class: 'inline-block border border-sub-color max-w-[160px] w-full rounded px-4 py-2 bg-white cursor-pointer hover:bg-sub-color hover:text-white duration-300' %>
      <%= link_to '削除する', board_path(@board), data: {turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm')}, class: 'inline-block border border-sub-color max-w-[160px] w-full rounded px-4 py-2 bg-white cursor-pointer hover:bg-sub-color hover:text-white duration-300' %>
    </div>・
  <% end %>
  <div class="flex gap-5 justify-center mt-10 text-center">
    <%= link_to '一覧へ戻る', boards_path, class: 'inline-block border border-sub-color max-w-[160px] w-full rounded px-4 py-2 bg-white cursor-pointer hover:bg-sub-color hover:text-white duration-300' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>こぎフォト</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@300;400;500;700;900&display=swap" rel="stylesheet">
</head>

<body class="flex flex-col min-h-screen">
  <% if logged_in? %>
    <%= render 'shared/header' %>
  <% else %>
    <%= render 'shared/before_login_header' %>
  <% end %>

  <%= render 'shared/flash_message' %>

  <%= yield %>

  <%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_before_login_header.html.erb
<header class="flex items-center justify-between h-16 px-4 bg-main-color shadow-md">
  <h1 class="font-bold">
    <%= link_to t('header.title'), root_path, class: '' %>
  </h1>
  <nav>
    <ul class="flex items-center gap-3">
      <li>
        <%= link_to t('header.to_register_page'), new_user_path, class: 'text-sm md:text-base hover:underline' %>
      </li>
      <li>
        <%= link_to t('header.login'), login_path, class: 'text-sm md:text-base hover:underline' %>
      </li>
    </ul>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <ul class="pl-5">
    <% object.errors.each do |error| %>
      <li class="text-red-600 text-base list-disc"><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="p-4 text-base md:p-5 <%= message_type == 'success' ? 'bg-green-100' : 'bg-red-100' %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center mt-auto p-10 bg-main-color text-base-content">
  <nav class="grid grid-flow-col gap-4">
    <%= link_to '利用規約', '#', class: 'text-sm md:text-base hover:underline' %>
    <%= link_to 'プライバシーポリシー', '#', class: 'text-sm md:text-base hover:underline' %>
  </nav>
  <p class="text-sm md:text-base">Copyright © 2024 - こぎフォト</p>
</footer>

app/views/shared/_header.html.erb
<header class="flex items-center justify-between h-16 px-4 bg-main-color shadow-sm">
  <h1 class="font-bold">
    <%= link_to t('header.title'), root_path, class: '' %>
  </h1>
  <nav>
    <ul class="flex items-center gap-3">
      <li>
        <%= link_to t('header.board_index'), boards_path, class: 'text-sm md:text-base hover:underline' %>
      </li>
      <li>
        <%= link_to t('header.board_create'), new_board_path, class: 'text-sm md:text-base hover:underline' %>
      </li>
      <li>
        <%= link_to t('header.logout'), logout_path, class: 'text-sm md:text-base hover:underline', data: { turbo_method: :delete } %>
      </li>
    </ul>
  </nav>
</header>

app/views/static_pages/top.html.erb
<div class="mx-auto my-10 max-w-7xl px-5">
  <div class="relative mx-auto max-w-3xl">
    <%= image_tag 'top-welcome.png', class: 'w-full object-cover' %>
    <p class="title">Welcome to <br>cogi photo!!</p>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="mx-auto my-10 max-w-3xl w-full px-5 md:my-20">
  <h1 class="text-3xl text-center "><%= t('.title') %></h1>
  <%= form_with url: login_path, class: 'grid grid-cols-1 gap-5 mt-10' do |f| %>
    <div class="grid grid-cols-1 gap-3">
      <%= f.label :email, class: 'font-medium' %>
      <%= f.email_field :email, class: 'border border-sub-color rounded text-base p-2' %>
    </div>
    <div class="grid grid-cols-1 gap-3">
      <%= f.label :password, class: 'font-medium' %>
      <%= f.password_field :password, class: 'border border-sub-color rounded text-base p-2' %>
    </div>
    <div class="my-10 text-center">
      <%= f.submit t('.login'), class: 'inline-block border border-sub-color max-w-[160px] w-full rounded px-4 py-2 bg-white cursor-pointer hover:bg-sub-color hover:text-white duration-300' %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="mx-auto my-10 max-w-3xl w-full px-5 md:my-20">
  <h1 class="text-3xl text-center "><%= t('.title') %></h1>
  <%= form_with model: @user, class: 'grid grid-cols-1 gap-5 mt-10' do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="grid grid-cols-1 gap-3">
      <%= f.label :name, class: 'font-medium' %>
      <%= f.text_field :name, class: 'border border-sub-color rounded w-full text-base p-2' %>
    </div>
    <div class="grid grid-cols-1 gap-3">
      <%= f.label :email, class: 'font-medium' %>
      <%= f.email_field :email, class: 'border border-sub-color rounded w-full text-base p-2' %>
    </div>
    <div class="grid grid-cols-1 gap-3">
      <%= f.label :password, class: 'font-medium' %>
      <%= f.password_field :password, class: 'border border-sub-color rounded w-full text-base p-2' %>
    </div>
    <div class="grid grid-cols-1 gap-3">
      <%= f.label :password_confirmation, class: 'font-medium' %>
      <%= f.password_field :password_confirmation, class: 'border border-sub-color rounded w-full text-base p-2' %>
    </div>
    <div class="my-10 text-center">
      <%= f.submit '登録', class: 'inline-block border border-sub-color max-w-[160px] w-full rounded px-4 py-2 bg-white cursor-pointer hover:bg-sub-color hover:text-white duration-300' %>
    </div>
  <% end %>
</div>